version: '3.9'

services:
  client:
    image: node:14-alpine
    volumes:
      - ./PFE/client:/app
    ports:
      - '3000:3000'
    command: sh -c "cd /app && npm install && npm start"
    depends_on:
      - server
  server:
    image: node:19-alpine
    volumes:
      - ./PFE/server:/app
    ports:
      - '3002:3002'
    command: sh -c "cd /app && npm install && npm start"
    depends_on:
      - mongodb
#    environment:
#      - MONGODB_URI=mongodb://mongodb:27017/adminAuthDB
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb_data:
