version: '3.9'
services:
  client:
    image: node:14-alpine
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    command: sh -c "cd /app && npm install && npm start"
    depends_on:
      - server
  server:
    image: node:19-alpine
    volumes:
      - ./server:/app
    ports:
      - '3002:3002'
    command: sh -c "cd /app && npm install && npm start"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
     ports:
       - '9200:9200'
       - '9300:9300'
     environment:
       - discovery.type=single-node
   logstash:
     image: docker.elastic.co/logstash/logstash:7.15.0
     volumes:
       - ./logstash/config:/usr/share/logstash/config
       - ./logstash/pipeline:/usr/share/logstash/pipeline
     ports:
       - '5000:5000'
     depends_on:
       - elasticsearch
     command: logstash -f /usr/share/logstash/pipeline/logstash.conf
   kibana:
     image: docker.elastic.co/kibana/kibana:7.15.0
     ports:
       - '5601:5601'
     depends_on:
       - elasticsearch          
volumes:
  mongodb_data:
